name: Monitor Diário Oficial RN

on:
  schedule:
  # A cada 6 horas - mais espaçado para evitar fila
  # 00:00 BRT -> 03:00 UTC
  - cron: '0 3 * * *'
  # 06:00 BRT -> 09:00 UTC  
  - cron: '0 9 * * *'
  # 12:00 BRT -> 15:00 UTC
  - cron: '0 15 * * *'
  # 18:00 BRT -> 21:00 UTC
  - cron: '0 21 * * *'
  workflow_dispatch: # Permite rodar manualmente pela aba Actions do GitHub

jobs:
  monitorar:
    runs-on: ubuntu-latest
    permissions:      # <-- A CORREÇÃO ESSENCIAL
      contents: write # <--
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Busca todo o histórico

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências Python
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Instalar navegadores Playwright
      run: python -m playwright install --with-deps chromium

    - name: Verificar se existe histórico
      run: |
        if [ -f "historico_alertas.json" ]; then
          echo "Arquivo de histórico encontrado:"
          cat historico_alertas.json
        else
          echo "Nenhum arquivo de histórico encontrado. Será criado um novo."
          echo "[]" > historico_alertas.json
        fi

    - name: Rodar o Bot de Monitoramento
      env:
        EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
        EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
        EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
      run: python bot.py

    - name: Verificar mudanças no histórico
      run: |
        echo "Conteúdo atual do histórico:"
        cat historico_alertas.json

    - name: Commit do histórico atualizado
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add historico_alertas.json
        if ! git diff --staged --quiet; then
          git commit -m "Atualiza histórico de alertas - $(date '+%d/%m/%Y %H:%M')"
          git push
          echo "Histórico atualizado e enviado para o repositório"
        else
          echo "Nenhuma mudança no histórico para fazer commit"
        fi