name: Monitor Diário Oficial RN

on:
  schedule:
    # Roda todos os dias às 9:00 UTC (6:00 no horário de Brasília)
    - cron: '0 9 * * *'
    # Roda todos os dias às 21:00 UTC (18:00 no horário de Brasília)
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  monitorar:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Instalar browsers e dependências do Playwright
        run: python -m playwright install --with-deps

      - name: 5. Rodar o Bot de Monitoramento
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        run: python bot.py

      - name: 6. Commit do histórico atualizado
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add historico_alertas.json
          git diff --staged --quiet || git commit -m "Atualiza histórico de alertas"
          git push
