name: Monitor Diário Oficial RN

on:
  schedule:
    # 9h UTC (6h Brasília)
    - cron: '0 9 * * *'
    # 21h UTC (18h Brasília)
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  monitorar:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-noble
      options: --user 1001
    timeout-minutes: 30

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar o Bot de Monitoramento
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        run: python bot.py

      - name: Commit do histórico atualizado
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add historico_alertas.json
          git diff --staged --quiet || git commit -m "Atualiza histórico de alertas"
          git push
